import React from 'react';
import {
  Boat,
  ShippingContainer,
  SquaresFour,
  Tray,
  UserFocus,
  Gauge,
  Gear,
  GearSix,
  MagnifyingGlass,
  UploadSimple,
  DownloadSimple,
  Play,
  SignOut,
  X,
  Check,
  CheckCircle,
  XCircle,
  Question,
  UserCheck,
  Prohibit,
  SpinnerGap,
  Buildings,
  User,
  Flag,
  Anchor,
  MapPin,
  Package,
  Scales,
  Scan,
  Paperclip,
  Files,
  FileText,
  FileCode,
  FileDashed,
  FunnelSimple,
  ArrowsClockwise,
  ChartLineUp,
  Sparkle,
  ShieldCheck,
  ArrowRight,
  ArrowLeft,
  ArrowUpRight,
  ArrowDownRight,
  Warning,
  WarningCircle,
  Receipt,
  EnvelopeSimple,
  GitDiff,
  Lock,
  Eye,
  EyeSlash,
  Lightning,
  Info,
  Sliders,
  FloppyDisk,
  PlugsConnected,
  GridFour,
  PaperPlaneTilt,
  CircleDashed,
  CaretDown,
  CaretUp,
  ClockCounterClockwise,
  Code,
  House,
  UserPlus,
  SignIn,
  SidebarSimple,
  ArrowLineLeft,
  ArrowLineRight,
} from '@phosphor-icons/react';

const ICONS = {
  Boat,
  Ship: Boat,
  ShippingContainer,
  SquaresFour,
  Tray,
  UserFocus,
  Gauge,
  Gear,
  GearSix,
  MagnifyingGlass,
  UploadSimple,
  DownloadSimple,
  Play,
  SignOut,
  X,
  Check,
  CheckCircle,
  XCircle,
  Question,
  UserCheck,
  Prohibit,
  SpinnerGap,
  Buildings,
  User,
  Flag,
  Anchor,
  MapPin,
  Package,
  Scales,
  Scan,
  Paperclip,
  Files,
  FileText,
  FileCode,
  FileDashed,
  FunnelSimple,
  ArrowsClockwise,
  ChartLineUp,
  Sparkle,
  ShieldCheck,
  ArrowRight,
  ArrowLeft,
  ArrowUpRight,
  ArrowDownRight,
  Warning,
  WarningCircle,
  Receipt,
  EnvelopeSimple,
  GitDiff,
  Lock,
  Eye,
  EyeSlash,
  Lightning,
  Info,
  Sliders,
  FloppyDisk,
  PlugsConnected,
  GridFour,
  PaperPlaneTilt,
  CircleDashed,
  CaretDown,
  CaretUp,
  ClockCounterClockwise,
  Code,
  House,
  UserPlus,
  SignIn,
  SidebarSimple,
  ArrowLineLeft,
  ArrowLineRight,
  // Common aliases
  gitCompare: GitDiff,
  gitDiff: GitDiff,
  fileText: FileText,
  receipt: Receipt,
  mail: EnvelopeSimple,
  envelope: EnvelopeSimple,
  alertTriangle: Warning,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  helpCircle: Question,
  userCheck: UserCheck,
  loader: SpinnerGap,
  spinner: SpinnerGap,
  alertCircle: WarningCircle,
  building: Buildings,
  user: User,
  flag: Flag,
  anchor: Anchor,
  mapPin: MapPin,
  box: Package,
  package: Package,
  scale: Scales,
  scales: Scales,
  scan: Scan,
  paperclip: Paperclip,
  files: Files,
  search: MagnifyingGlass,
  filter: FunnelSimple,
  download: DownloadSimple,
  upload: UploadSimple,
  refresh: ArrowsClockwise,
  chart: ChartLineUp,
  sparkles: Sparkle,
  shield: ShieldCheck,
  gear: GearSix,
  signout: SignOut,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  arrowUp: ArrowUpRight,
  arrowDown: ArrowDownRight,
  check: Check,
  x: X,
  sidebar: SidebarSimple,
  panelLeft: SidebarSimple,
};

/**
 * Universal Phosphor Duotone Icon Wrapper
 */
export function PhosphorIcon({
  name,
  size = 20,
  weight = 'duotone',
  className = '',
  color,
  style,
  ...props
}) {
  let IconComponent = ICONS[name];
  if (!IconComponent && typeof name === 'string') {
    const PascalName = name.charAt(0).toUpperCase() + name.slice(1);
    IconComponent = ICONS[PascalName];
  }

  if (!IconComponent) {
    IconComponent = CircleDashed;
  }

  return (
    <IconComponent
      size={size}
      weight={weight}
      color={color}
      className={`shrink-0 transition-colors ${className}`}
      style={style}
      {...props}
    />
  );
}

export default PhosphorIcon;
